apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: lms-backend
build:
  local:
    push: false
  artifacts:
    - image: auth-service
      context: .
      docker:
        dockerfile: packages/auth-service/Dockerfile
      sync:
        manual:
          - src: 'packages/auth-service/src/**/*.ts'
            dest: '/app'
    - image: user-service
      context: .
      docker:
        dockerfile: packages/user-service/Dockerfile
      sync:
        manual:
          - src: 'packages/user-service/src/**/*.ts'
            dest: '/app'
    - image: course-service
      context: .
      docker:
        dockerfile: packages/course-service/Dockerfile
      sync:
        manual:
          - src: 'packages/course-service/src/**/*.ts'
            dest: '/app'
    - image: media-service
      context: .
      docker:
        dockerfile: packages/media-service/Dockerfile
      sync:
        manual:
          - src: 'packages/media-service/src/**/*.ts'
            dest: '/app'
    - image: mcq-service
      context: .
      docker:
        dockerfile: packages/mcq-service/Dockerfile
      sync:
        manual:
          - src: 'packages/mcq-service/src/**/*.ts'
            dest: '/app'
    - image: coding-service
      context: .
      docker:
        dockerfile: packages/coding-service/Dockerfile
      sync:
        manual:
          - src: 'packages/coding-service/src/**/*.ts'
            dest: '/app'
    - image: project-review-service
      context: .
      docker:
        dockerfile: packages/project-review-service/Dockerfile
      sync:
        manual:
          - src: 'packages/project-review-service/src/**/*.ts'
            dest: '/app'
    - image: chat-service
      context: .
      docker:
        dockerfile: packages/chat-service/Dockerfile
      sync:
        manual:
          - src: 'packages/chat-service/src/**/*.ts'
            dest: '/app'
    - image: frontend
      context: .
      docker:
        dockerfile: packages/frontend/Dockerfile
manifests:
  kustomize:
    paths:
      - k8s
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: chat-service
    port: 80
    localPort: 5007
  - resourceType: service
    resourceName: project-review-service
    port: 80
    localPort: 5006
  - resourceType: service
    resourceName: auth-service
    port: 80
    localPort: 5000
