apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-deployment
  labels:
    name: coding-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding
  template:
    metadata:
      labels:
        app: coding
    spec:
      containers:
        - image: coding-service
          name: coding-main
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: '120m'
              memory: '120M'
            limits:
              cpu: '250m'
              memory: '250M'
          livenessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5005
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: ACCESS_TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: ACCESS_TOKEN_PUBLIC_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: database
                  key: CODING_DB
            - name: JUDGE_URL
              value: 'http://judge-service'
            - name: PORT
              value: '5005'
            - name: NODE_ENV
              value: 'production'
          ports:
            - containerPort: 5005
              name: http
